#!/bin/bash

set -e

# Helper for searching code base without searching through external code

cd "$(git rev-parse --show-toplevel)"

exec ack "$@" \
    --ignore-directory .tox \
    --ignore-directory .mypy_cache \
    --ignore-directory .dmypy.json \
    --ignore-directory dist \
    --ignore-directory build \
    --ignore-directory venvstarter.egg-info \
    --ignore-directory tools \
    --ignore-directory docs/.sphinx-build \
    --ignore-directory docs/_build 
