#!/usr/bin/env python3

import runpy
import os

this_dir = os.path.dirname(__file__)

manager = runpy.run_path(os.path.join(this_dir, "..", "venvstarter.py"))["manager"]

manager.add_requirements_file("{here}", "requirements.txt")
manager.add_local_dep(
    "{here}", "..", name="venvstarter=={version}", version_file=["venvstarter.py"]
)

manager.min_python(3.6).run("sphinx-build")
