#!/usr/bin/env python3

from venvstarter import ignite
import runpy
import os

this_dir = os.path.dirname(__file__)

venvstarter_version = runpy.run_path(
    os.path.join(this_dir, "..", "venvstarter", "__init__.py")
)["VERSION"]

with open(os.path.join(this_dir, "requirements.txt"), "r") as fle:
    deps = [line.strip() for line in fle.readlines() if line.strip()]

deps.append(f"-e file:{this_dir}/..#egg=venvstarter=={venvstarter_version}")

ignite(this_dir, "sphinx-build", deps=deps, min_python_version=3.6)
