---

name: Tests on Linux

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Get pyenv
        uses: gabrielfalcao/pyenv-action@v16

      - name: Available pyenv versions
        shell: bash
        run: |
          pyenv install --list

      - name: Update system pip
        shell: bash
        run: |
          python3 -m pip install pip>=23 --upgrade

      - name: Install venvstarter in venv
        shell: bash
        run: |
          VENVSTARTER_ONLY_MAKE_VENV=1 ./test.sh
          tools/.python/bin/python -m pip install pip>=23 --upgrade

      - name: Restore pyenv cache cache
        id: python_cache
        uses: actions/cache/restore@v3
        with:
          key: ${{ runner.os }}-python-3.7.17_3.8.17_3.9.17_3.10.12_3.11.4
          path: |
            /opt/hostedtoolcache/pyenv_root
          restore-keys:
            ${{ runner.os }}-python-

      - name: Install python versions
        if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          set -e

          pyenv --version

          for version in 3.7.17 3.8.17 3.9.17 3.10.12 3.11.4; do
            pyenv install $version
          done

          pyenv rehash

      - name: Save pyenv cache
        id: save_python_cache
        uses: actions/cache/save@v3
        with:
          key: ${{ steps.python_cache.outputs.cache-primary-key }}
          if: always()
          path: |
            /opt/hostedtoolcache/pyenv_root

      - name: Find python versions
        run: |
          set -e

          pyenv versions
          V37=$(pyenv whence python3.7)
          V38=$(pyenv whence python3.8)
          V39=$(pyenv whence python3.9)
          V310=$(pyenv whence python3.10)
          V311=$(pyenv whence python3.11)

          ROOT=$(pyenv root)

          cat <<EOF > pythons.json
          {
            "python3.7": "$ROOT/versions/$V37/bin/python",
            "python3.8": "$ROOT/versions/$V38/bin/python",
            "python3.9": "$ROOT/versions/$V39/bin/python",
            "python3.10": "$ROOT/versions/$V310/bin/python",
            "python3.11": "$ROOT/versions/$V311/bin/python"
          }
          EOF

      - name: Found pythons
        run: |
          cat pythons.json

      - name: Install venvstarter in system
        shell: bash
        run: |
          python3 -m pip install -e '.[tests]'

      - name: Run the tests
        run: |
          ./test.sh
