---

name: Tests on Linux

on:
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-linux_ci
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Restore pyenv cache cache
        id: python_cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-python-3.10.11_3.11.9_3.12.4
          path: |
            ~/.pyenv
          restore-keys:
            ${{ runner.os }}-python-

      - name: Get pyenv
        shell: bash
        run: |
          if [[ ! -d ~/.pyenv ]]; then
            curl https://pyenv.run | bash
          fi

      - name: pyenv on PATH
        shell: bash
        run: |
          export PYENV_ROOT="$HOME/.pyenv"
          [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
          eval "$(pyenv init -)"

          echo "PATH=$PATH" >> $GITHUB_ENV
          echo "PYENV_ROOT=$PYENV_ROOT" >> $GITHUB_ENV

      - name: Available pyenv versions
        shell: bash
        run: |
          eval "$(pyenv init -)"
          pyenv update
          pyenv install --list

      - name: Install python versions
        shell: bash
        run: |
          set -e

          eval "$(pyenv init -)"
          pyenv --version

          pyenv install 3.10.11 --skip-existing
          pyenv install 3.11.9 --skip-existing
          pyenv install 3.12.4 --skip-existing

          pyenv rehash

      - name: Save pyenv cache
        id: save_python_cache
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.python_cache.outputs.cache-primary-key }}
          path: |
            ~/.pyenv

      - name: Update system pip
        shell: bash
        run: |
          python3 -m pip install pip>=23 --upgrade

      - name: Install venvstarter in venv
        shell: bash
        run: |
          VENVSTARTER_ONLY_MAKE_VENV=1 ./test.sh
          tools/.python/bin/python -m pip install pip>=23 --upgrade

      - name: Find python versions
        run: |
          set -e

          eval "$(pyenv init -)"
          pyenv versions
          V310=$(pyenv whence python3.10 | head -n1)
          V311=$(pyenv whence python3.11 | head -n1)
          V312=$(pyenv whence python3.12 | head -n1)

          ROOT=$(pyenv root)

          cat <<EOF > pythons.json
          {
            "python3.10": "$ROOT/versions/$V310/bin/python",
            "python3.11": "$ROOT/versions/$V311/bin/python",
            "python3.12": "$ROOT/versions/$V312/bin/python"
          }
          EOF

      - name: Found pythons
        run: |
          cat pythons.json

      - name: Install venvstarter in system
        shell: bash
        run: |
          python3 -m pip install -e '.[tests]'

      - name: Run the tests
        run: |
          ./test.sh
