---

name: Tests on MacOS

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, "3.10"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Fix permissions for /opt so cache works
        shell: bash
        run: |
          sudo chmod -R a+rwx /opt

      - name: Get pyenv
        uses: gabrielfalcao/pyenv-action@v8

      - name: Cache Python
        id: python_cache
        uses: actions/cache@v2
        with:
          key: python3.6.13_3.7.10_3.8.10_3.9.5_3.10.0
          path: |
            /opt/hostedtoolcache/pyenv_root
            ~/hostedtoolcache/pyenv_root

      - name: Install python versions
        if: steps.python_cache.outputs.cache-hit != 'true'
        run: |
          set -e

          pyenv --version

          unset CPPFLAG
          unset LDFLAGS
          unset CFLAGS

          curl -sSL https://github.com/python/cpython/commit/8ea6353.patch\?full_index\=1 > /tmp/patch

          pyenv install --patch 3.6.13 < /tmp/patch
          for version in 3.7.10 3.8.10 3.9.5 3.10.0b1; do
            pyenv install $version
          done

          pyenv rehash

      - name: Find python versions
        run: |
          set -e

          pyenv versions
          V36=$(pyenv whence python3.6)
          V37=$(pyenv whence python3.7)
          V38=$(pyenv whence python3.8)
          V39=$(pyenv whence python3.9)
          V310=$(pyenv whence python3.10)

          ROOT=$(pyenv root)

          cat <<eof > pythons.json
          {
            "python3.6": "$ROOT/versions/$V36/bin/python",
            "python3.7": "$ROOT/versions/$V37/bin/python",
            "python3.8": "$ROOT/versions/$V38/bin/python",
            "python3.9": "$ROOT/versions/$V39/bin/python",
            "python3.10": "$ROOT/versions/$V310/bin/python"
          }
          eof

      - name: found pythons
        run: |
          cat pythons.json

      - name: install venvstarter
        run: |
          python3 -m pip install -e ".[tests]"

      - name: run the tests
        run: |
          ./test.sh
