---

name: Tests on Windows

on:
  pull_request: {}
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-windows_ci
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update system pip
        shell: bash
        run: |
          python3 -m pip install pip>=23 --upgrade

      - name: Install venvstarter in venv
        shell: bash
        run: |
          # TODO: Make it so venvstarter has option to ensure pip before checking deps
          python3 -c "__import__('venv').create(str(__import__('pathlib').Path('tools', '.python').resolve()), with_pip=False)"
          tools/.python/Scripts/python.exe -m ensurepip
          tools/.python/Scripts/python.exe -m pip install pip>=23 --upgrade
          VENVSTARTER_ONLY_MAKE_VENV=1 ./test.sh

      - name: Restore pyenv cache cache
        id: python_cache
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-python-3.10.11_3.11.94_3.12.4
          path: |
            ~/.pyenv
          restore-keys:
            ${{ runner.os }}-python-

      - name: Get pyenv
        shell: bash
        run: |
          if [[ ! -d $HOME\\.pyenv ]]; then
            python3 -m pip install pyenv-win --target $HOME\\.pyenv
          fi

      - name: pyenv on PATH
        shell: bash
        run: |
          echo "PYENV=$USERPROFILE\.pyenv\pyenv-win\\" >> $GITHUB_ENV
          echo "PYENV_HOME=$USERPROFILE\.pyenv\pyenv-win\\" >> $GITHUB_ENV
          echo "$USERPROFILE\.pyenv\pyenv-win\\bin\\" >> $GITHUB_PATH

      - name: Available pyenv versions
        shell: bash
        run: |
          pyenv update
          pyenv install --list

      - name: Install python versions
        shell: bash
        run: |
          set -e

          pyenv --version

          pyenv install 3.10.11 --skip-existing
          pyenv install 3.11.9 --skip-existing
          pyenv install 3.12.4 --skip-existing

          pyenv rehash

      - name: Save pyenv cache
        id: save_python_cache
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.python_cache.outputs.cache-primary-key }}
          path: |
            ~/.pyenv

      - name: Find python versions
        shell: bash
        run: |
          set -ex

          ROOT=~/.pyenv
          ls $ROOT
          pyenv whence python
          V310=$(pyenv whence python3.10 | head -n1)
          V311=$(pyenv whence python3.11 | head -n1)
          V312=$(pyenv whence python3.12 | head -n1)

          cat <<EOF > pythons.json
          {
            "python3.10": "~/.pyenv/pyenv-win/versions/$V310/python.exe",
            "python3.11": "~/.pyenv/pyenv-win/versions/$V311/python.exe",
            "python3.12": "~/.pyenv/pyenv-win/versions/$V312/python.exe"
          }
          EOF

      - name: Found pythons
        shell: bash
        run: |
          cat pythons.json

      - name: Install venvstarter in system
        shell: bash
        run: |
          python3 -m pip install -e '.[tests]'

      - name: Run the tests
        shell: bash
        run: |
          ./test.sh
